id diag4 =  - prop( - p1 - p3 + k1)*propmt(k1)*propmt( - p1 + k1)*propmt(p2 + 
      k1)*Tr(a99,a97)*LoopF(1,eps3, - p1 - p3 + k1,eps4,p2 + k1,eps2,k1,eps1)*
      DiaMatch(4)*mt*vq^2*g^2 - prop( - p1 - p3 + k1)*propmt(k1)*propmt( - p1
       + k1)*propmt(p2 + k1)*Tr(a99,a97)*LoopF(1,eps3, - p1 - p3 + k1,eps4,p2
       + k1,eps2,k1,eps1, - p1 + k1)*DiaMatch(4)*vq^2*g^2 - prop( - p1 - p3 + 
      k1)*propmt(k1)*propmt( - p1 + k1)*propmt(p2 + k1)*Tr(a99,a97)*LoopF(1,
      eps3, - p1 - p3 + k1,eps4,p2 + k1,eps2,eps1)*DiaMatch(4)*mt^2*vq^2*g^2
       - prop( - p1 - p3 + k1)*propmt(k1)*propmt( - p1 + k1)*propmt(p2 + k1)*
      Tr(a99,a97)*LoopF(1,eps3, - p1 - p3 + k1,eps4,p2 + k1,eps2,eps1, - p1 + 
      k1)*DiaMatch(4)*mt*vq^2*g^2 - prop( - p1 - p3 + k1)*propmt(k1)*propmt(
       - p1 + k1)*propmt(p2 + k1)*Tr(a99,a97)*LoopF(1,eps3, - p1 - p3 + k1,
      eps4,eps2,k1,eps1)*DiaMatch(4)*mt^2*vq^2*g^2 - prop( - p1 - p3 + k1)*
      propmt(k1)*propmt( - p1 + k1)*propmt(p2 + k1)*Tr(a99,a97)*LoopF(1,eps3,
       - p1 - p3 + k1,eps4,eps2,k1,eps1, - p1 + k1)*DiaMatch(4)*mt*vq^2*g^2 - 
      prop( - p1 - p3 + k1)*propmt(k1)*propmt( - p1 + k1)*propmt(p2 + k1)*Tr(
      a99,a97)*LoopF(1,eps3, - p1 - p3 + k1,eps4,eps2,eps1)*DiaMatch(4)*mt^3*
      vq^2*g^2 - prop( - p1 - p3 + k1)*propmt(k1)*propmt( - p1 + k1)*propmt(p2
       + k1)*Tr(a99,a97)*LoopF(1,eps3, - p1 - p3 + k1,eps4,eps2,eps1, - p1 + 
      k1)*DiaMatch(4)*mt^2*vq^2*g^2 + 1/6*prop( - p1 - p3 + k1)*propmt(k1)*
      propmt( - p1 + k1)*propmt(p2 + k1)*Tr(a99,a97)*LoopF(1,eps3, - p1 - p3
       + k1,nu1,ro1,sigma1,p2 + k1,eps2,k1,eps1)*DiaMatch(4)*e_(eps4,nu1,ro1,
      sigma1)*mt*vq*aq*g^2 + 1/6*prop( - p1 - p3 + k1)*propmt(k1)*propmt( - p1
       + k1)*propmt(p2 + k1)*Tr(a99,a97)*LoopF(1,eps3, - p1 - p3 + k1,nu1,ro1,
      sigma1,p2 + k1,eps2,k1,eps1, - p1 + k1)*DiaMatch(4)*e_(eps4,nu1,ro1,
      sigma1)*vq*aq*g^2 + 1/6*prop( - p1 - p3 + k1)*propmt(k1)*propmt( - p1 + 
      k1)*propmt(p2 + k1)*Tr(a99,a97)*LoopF(1,eps3, - p1 - p3 + k1,nu1,ro1,
      sigma1,p2 + k1,eps2,eps1)*DiaMatch(4)*e_(eps4,nu1,ro1,sigma1)*mt^2*vq*aq
      *g^2 + 1/6*prop( - p1 - p3 + k1)*propmt(k1)*propmt( - p1 + k1)*propmt(p2
       + k1)*Tr(a99,a97)*LoopF(1,eps3, - p1 - p3 + k1,nu1,ro1,sigma1,p2 + k1,
      eps2,eps1, - p1 + k1)*DiaMatch(4)*e_(eps4,nu1,ro1,sigma1)*mt*vq*aq*g^2
       + 1/6*prop( - p1 - p3 + k1)*propmt(k1)*propmt( - p1 + k1)*propmt(p2 + 
      k1)*Tr(a99,a97)*LoopF(1,eps3, - p1 - p3 + k1,nu1,ro1,sigma1,eps2,k1,eps1
      )*DiaMatch(4)*e_(eps4,nu1,ro1,sigma1)*mt^2*vq*aq*g^2 + 1/6*prop( - p1 - 
      p3 + k1)*propmt(k1)*propmt( - p1 + k1)*propmt(p2 + k1)*Tr(a99,a97)*
      LoopF(1,eps3, - p1 - p3 + k1,nu1,ro1,sigma1,eps2,k1,eps1, - p1 + k1)*
      DiaMatch(4)*e_(eps4,nu1,ro1,sigma1)*mt*vq*aq*g^2 + 1/6*prop( - p1 - p3
       + k1)*propmt(k1)*propmt( - p1 + k1)*propmt(p2 + k1)*Tr(a99,a97)*LoopF(1
      ,eps3, - p1 - p3 + k1,nu1,ro1,sigma1,eps2,eps1)*DiaMatch(4)*e_(eps4,nu1,
      ro1,sigma1)*mt^3*vq*aq*g^2 + 1/6*prop( - p1 - p3 + k1)*propmt(k1)*
      propmt( - p1 + k1)*propmt(p2 + k1)*Tr(a99,a97)*LoopF(1,eps3, - p1 - p3
       + k1,nu1,ro1,sigma1,eps2,eps1, - p1 + k1)*DiaMatch(4)*e_(eps4,nu1,ro1,
      sigma1)*mt^2*vq*aq*g^2 + 1/6*prop( - p1 - p3 + k1)*propmt(k1)*propmt( - 
      p1 + k1)*propmt(p2 + k1)*Tr(a99,a97)*LoopF(1,nu2,ro2,sigma2, - p1 - p3
       + k1,eps4,p2 + k1,eps2,k1,eps1)*DiaMatch(4)*e_(eps3,nu2,ro2,sigma2)*mt*
      vq*aq*g^2 + 1/6*prop( - p1 - p3 + k1)*propmt(k1)*propmt( - p1 + k1)*
      propmt(p2 + k1)*Tr(a99,a97)*LoopF(1,nu2,ro2,sigma2, - p1 - p3 + k1,eps4,
      p2 + k1,eps2,k1,eps1, - p1 + k1)*DiaMatch(4)*e_(eps3,nu2,ro2,sigma2)*vq*
      aq*g^2 + 1/6*prop( - p1 - p3 + k1)*propmt(k1)*propmt( - p1 + k1)*propmt(
      p2 + k1)*Tr(a99,a97)*LoopF(1,nu2,ro2,sigma2, - p1 - p3 + k1,eps4,p2 + k1
      ,eps2,eps1)*DiaMatch(4)*e_(eps3,nu2,ro2,sigma2)*mt^2*vq*aq*g^2 + 1/6*
      prop( - p1 - p3 + k1)*propmt(k1)*propmt( - p1 + k1)*propmt(p2 + k1)*Tr(
      a99,a97)*LoopF(1,nu2,ro2,sigma2, - p1 - p3 + k1,eps4,p2 + k1,eps2,eps1,
       - p1 + k1)*DiaMatch(4)*e_(eps3,nu2,ro2,sigma2)*mt*vq*aq*g^2 + 1/6*prop(
       - p1 - p3 + k1)*propmt(k1)*propmt( - p1 + k1)*propmt(p2 + k1)*Tr(a99,
      a97)*LoopF(1,nu2,ro2,sigma2, - p1 - p3 + k1,eps4,eps2,k1,eps1)*DiaMatch(
      4)*e_(eps3,nu2,ro2,sigma2)*mt^2*vq*aq*g^2 + 1/6*prop( - p1 - p3 + k1)*
      propmt(k1)*propmt( - p1 + k1)*propmt(p2 + k1)*Tr(a99,a97)*LoopF(1,nu2,
      ro2,sigma2, - p1 - p3 + k1,eps4,eps2,k1,eps1, - p1 + k1)*DiaMatch(4)*e_(
      eps3,nu2,ro2,sigma2)*mt*vq*aq*g^2 + 1/6*prop( - p1 - p3 + k1)*propmt(k1)
      *propmt( - p1 + k1)*propmt(p2 + k1)*Tr(a99,a97)*LoopF(1,nu2,ro2,sigma2,
       - p1 - p3 + k1,eps4,eps2,eps1)*DiaMatch(4)*e_(eps3,nu2,ro2,sigma2)*mt^3
      *vq*aq*g^2 + 1/6*prop( - p1 - p3 + k1)*propmt(k1)*propmt( - p1 + k1)*
      propmt(p2 + k1)*Tr(a99,a97)*LoopF(1,nu2,ro2,sigma2, - p1 - p3 + k1,eps4,
      eps2,eps1, - p1 + k1)*DiaMatch(4)*e_(eps3,nu2,ro2,sigma2)*mt^2*vq*aq*g^2
       - 1/36*prop( - p1 - p3 + k1)*propmt(k1)*propmt( - p1 + k1)*propmt(p2 + 
      k1)*Tr(a99,a97)*LoopF(1,nu2,ro2,sigma2, - p1 - p3 + k1,nu3,ro3,sigma3,p2
       + k1,eps2,k1,eps1)*DiaMatch(4)*e_(eps3,nu2,ro2,sigma2)*e_(eps4,nu3,ro3,
      sigma3)*mt*aq^2*g^2 - 1/36*prop( - p1 - p3 + k1)*propmt(k1)*propmt( - p1
       + k1)*propmt(p2 + k1)*Tr(a99,a97)*LoopF(1,nu2,ro2,sigma2, - p1 - p3 + 
      k1,nu3,ro3,sigma3,p2 + k1,eps2,k1,eps1, - p1 + k1)*DiaMatch(4)*e_(eps3,
      nu2,ro2,sigma2)*e_(eps4,nu3,ro3,sigma3)*aq^2*g^2 - 1/36*prop( - p1 - p3
       + k1)*propmt(k1)*propmt( - p1 + k1)*propmt(p2 + k1)*Tr(a99,a97)*LoopF(1
      ,nu2,ro2,sigma2, - p1 - p3 + k1,nu3,ro3,sigma3,p2 + k1,eps2,eps1)*
      DiaMatch(4)*e_(eps3,nu2,ro2,sigma2)*e_(eps4,nu3,ro3,sigma3)*mt^2*aq^2*
      g^2 - 1/36*prop( - p1 - p3 + k1)*propmt(k1)*propmt( - p1 + k1)*propmt(p2
       + k1)*Tr(a99,a97)*LoopF(1,nu2,ro2,sigma2, - p1 - p3 + k1,nu3,ro3,sigma3
      ,p2 + k1,eps2,eps1, - p1 + k1)*DiaMatch(4)*e_(eps3,nu2,ro2,sigma2)*e_(
      eps4,nu3,ro3,sigma3)*mt*aq^2*g^2 - 1/36*prop( - p1 - p3 + k1)*propmt(k1)
      *propmt( - p1 + k1)*propmt(p2 + k1)*Tr(a99,a97)*LoopF(1,nu2,ro2,sigma2,
       - p1 - p3 + k1,nu3,ro3,sigma3,eps2,k1,eps1)*DiaMatch(4)*e_(eps3,nu2,ro2
      ,sigma2)*e_(eps4,nu3,ro3,sigma3)*mt^2*aq^2*g^2 - 1/36*prop( - p1 - p3 + 
      k1)*propmt(k1)*propmt( - p1 + k1)*propmt(p2 + k1)*Tr(a99,a97)*LoopF(1,
      nu2,ro2,sigma2, - p1 - p3 + k1,nu3,ro3,sigma3,eps2,k1,eps1, - p1 + k1)*
      DiaMatch(4)*e_(eps3,nu2,ro2,sigma2)*e_(eps4,nu3,ro3,sigma3)*mt*aq^2*g^2
       - 1/36*prop( - p1 - p3 + k1)*propmt(k1)*propmt( - p1 + k1)*propmt(p2 + 
      k1)*Tr(a99,a97)*LoopF(1,nu2,ro2,sigma2, - p1 - p3 + k1,nu3,ro3,sigma3,
      eps2,eps1)*DiaMatch(4)*e_(eps3,nu2,ro2,sigma2)*e_(eps4,nu3,ro3,sigma3)*
      mt^3*aq^2*g^2 - 1/36*prop( - p1 - p3 + k1)*propmt(k1)*propmt( - p1 + k1)
      *propmt(p2 + k1)*Tr(a99,a97)*LoopF(1,nu2,ro2,sigma2, - p1 - p3 + k1,nu3,
      ro3,sigma3,eps2,eps1, - p1 + k1)*DiaMatch(4)*e_(eps3,nu2,ro2,sigma2)*e_(
      eps4,nu3,ro3,sigma3)*mt^2*aq^2*g^2;
